[project]
name = "icedyno"
version = "0.1.0"
description = "HES Capstone: Short-term forecasting of artic sea-ice boundaries"
authors = ["Julieanna Bacon <julieannabacon2014@gmail.com>", "Soolu Thomas <sot204@g.harvard.edu>", "Brendon Gory <brg294@g.harvard.edu>", "Matthew Thanos <mpt986@g.harvard.edu>", "Ruchi Asthana <rua490@g.harvard.edu>"]
channels = ["conda-forge"]
platforms = ["win-64", "linux-64", "osx-64", "osx-arm64"]

[tasks]

[dependencies]
seaborn = ">=0.12.2,<0.14"
tensorflow = ">=1.14.0,<2.16"
jupyterlab = ">=3.6.7,<4.2"
h5py = ">=3.7.0,<3.11"
mkdocs = ">=1.5.3,<1.6"
pandas = ">=1.3.5,<2.3"
pip = ">=24.0,<25"
xarray = ">=0.20.2,<2024.4"
mkdocstrings = ">=0.23.0,<0.25"
gdal = ">=3.5.0,<3.9"
h5netcdf = ">=1.1.0,<1.4"
luigi = ">=3.1.1,<3.6"
pyproj = ">=3.2.1,<3.7"
pre-commit = ">=2.20.0,<3.8"
plotly = ">=5.19.0,<5.20"
netCDF4 = ">=1.6.0,<1.7"
geopandas = ">=0.10.2,<0.15"
numba = ">=0.56.3,<0.60"
beautifulsoup4 = ">=4.12.3,<4.13"
pytest = ">=7.4.4,<8.2"
toml = ">=0.10.2,<0.11"
matplotlib = ">=3.5.3,<3.9"
