[project]
name = "icedyno"
version = "0.1.0"
description = "Add a short description here"
authors = ["Julieanna Bacon <julieannabacon2014@gmail.com>"]
channels = ["conda-forge"]
platforms = ["linux-64"]

[tasks]

[dependencies]
pre-commit = ">=3.6.0,<3.7"
