[project]
name = "icedyno"
version = "0.1.0"
description = "HES Capstone: Short-term forecasting of artic sea-ice boundaries"
authors = ["Julieanna Bacon <julieannabacon2014@gmail.com>", "Soolu Thomas <sot204@g.harvard.edu>", "Brendon Gory <brg294@g.harvard.edu>", "Matthew Thanos <mpt986@g.harvard.edu>", "Ruchi Asthana <rua490@g.harvard.edu>"]
channels = ["conda-forge"]
platforms = ["win-64", "linux-64", "osx-64", "osx-arm64"]

[tasks]

[dependencies]
pre-commit = ">=3.6.0,<3.7"
pytest = ">=8.0.0,<8.1"
mkdocs = ">=1.5.3,<1.6"
mkdocstrings = ">=0.24.0,<0.25"
jupyterlab = ">=4.1.0,<4.2"
matplotlib = ">=3.8.2,<3.9"
beautifulsoup4 = ">=4.12.3,<4.13"
