[CropRotateNetCDF]
# Full relative directory is data/input_dir, data/output_dir
input_dir = "ims_1km"

# Change this output_dir name to reflect the window size and center coordinates selected
# Example: _50000x_15000y
output_dir = "ims_netcdf_1km_cropped_1_000km_window"

# Final shape will be (window_size*2, window_size*2)
window_size = 1000 #km

# Longitude, latitude coordinates IN DEGREES for center of cropped window. 
# Defaults to center of current grid system if either is "None"
center_latitude = 74.0
center_longitude = -140.0
