[project]
name = "unet_model"
version = "0.1.0"
description = "Add a short description here"
authors = ["Julieanna Bacon <julieannabacon2014@gmail.com>"]
channels = ["conda-forge"]
platforms = ["linux-64"]

[tasks]

[dependencies]
tensorflow = ">=2.6.2,<2.7"
pandas = ">=1.4.4,<1.5"
seaborn = ">=0.12.2,<0.13"
matplotlib = ">=3.5.3,<3.6"
notebook = ">=7.1.2,<7.2"
numpy = ">=1.19.5,<1.20"
scikit-learn = ">=1.1.2,<1.2"
xarray = ">=2022.9.0,<2022.10"
h5netcdf = ">=1.3.0,<1.4"
scikit-image = ">=0.19.3,<0.20"
