name: Deploy mkdocs

on:
  push:
    branches:
      - main

env:
  PYTHON_VERSION: "3.10"
  PIXI_VERSION: "v0.13.0"

jobs:
  deploy-docs:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v3

      - name: Configure Git Credentials
        run: |
          git config user.name github-actions[bot]
          git config user.email github-actions[bot]@users.noreply.github.com

      - name: Install Python
        uses: actions/setup-python@v4
        with:
          python-version: ${{ env.PYTHON_VERSION }}

      - name: Install Pixi
        uses: prefix-dev/setup-pixi@v0.5.1 
        with:
          pixi-version: ${{ env.PIXI_VERSION }} 
          cache: true
          cache-write: ${{ github.event_name == 'push' && github.ref_name == 'main' }}

      - name: Install repository
        run: |
          pixi install
    
      - name: Build and deploy docs
        run: |
          git remote add gh-token "https://SooluThomas:${{ secrets.GH_TOKEN }}@github.com/NOAA-HES-Capstone/icedyno.git"
          git fetch gh-token && git fetch gh-token gh-pages:gh-pages
          pixi run mkdocs build
          pixi run mkdocs gh-deploy --force --clean --verbose --remote-name gh-token
