name: Code Style Check
# If your code has failed this workflow, you need to install the pre-commit hooks and run `pixi run pre-commit run --all-files`, adding and committing those changes.
# Please see docs/setup.md for more information on installing and what the committing process looks like.

on:
  push:
    branches:
      - main
  pull_request:
    types:
      - opened
      - synchronize

env:
  PYTHON_VERSION: "3.10"

jobs:
  Check-linter-status:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v3

      - name: Install Python
        uses: actions/setup-python@v4
        with:
          python-version: ${{ env.PYTHON_VERSION }}

      - name: Install pre-commit
        run: pip install pre-commit

      - name: Run pre-commit hooks
        run: pre-commit run --all-files --show-diff-on-failure
