name: Install Python, pixi, and project

on:
  push:
    branches:
      - main
  pull_request:
    types:
      - opened
      - synchronize

env:
  PYTHON_VERSION: "3.10"
  PIXI_VERSION: "v0.13.0"

jobs:
  Install-Informatics-Pipeline:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v3

      - name: Install Python
        uses: actions/setup-python@v4
        with:
          python-version: ${{ env.PYTHON_VERSION }}

      - name: Install Pixi
        uses: prefix-dev/setup-pixi@v0.5.1
        with:
          pixi-version: ${{ env.PIXI_version }} 
          cache: true

      - name: Install repository
        run: |
          pixi install

      - name: Run pytest
        run: |
          pixi run python -m pytest -v
